### ISSUE TITLE
UI - change channel while editing a rhythm 

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#11]
v1.0.0

When editing a rhythm make it so that when on presses the tap button it leaves the editor.

When editing a rhythm make it so that when on presses another rhythm button it switches to this rhythm

**Comment by ArthurGibert** [comment]
Suggestion 
I would make it so that the output setting are set by being in the current channel and press the config menu. (2 interaction)
This would make it more direct because here one needs to click on config, other, outputs, select the channel (4 interaction)

**Comment by lucblender** [comment]
> Suggestion To access channel setting one should press the channel button and then config. (2 interaction) This would make it more direct because here one needs to click on config, other, outputs, select the channel (4 interaction)

Split into another issue #21
