### ISSUE TITLE
Bug - Mute and Fill hanging

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#13]
v1.0.0

There is an isssue with the mute and fill macro.

1 - Assign one of the pads to Mute or Fill
2 - Mute or fill using the macro mode
3 - Assign the pad to something else

Result the rhythms remain in mute/fill mode and can't be edited

Suggestion: Reset mute/fill of the rhythm when the macro on this pad is changed

**Comment by lucblender** [comment]
Fixed in 5ae6ee9 , can be tested in pre-release [v1.2.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.2.0_pre)
