### ISSUE TITLE
Enhancement - CV input behaviour should act like an offset

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#14]
v1.0.0

I expect that it has something to do with the voltage range selection.

When noting is plugged in the CV and in +/-5V the minimum length that one can set is 15 beats long.

When setting CV using another voltage range, one losses the rhythm that was previously set and the rhythm defaults to 1 : 1

The expected behaviour would be that if no CV or 0V is sent to the input nothing should change. The CV should be an offset to what was set in the first place. If you would like to have different CV range selection I would do so by having a selection of amplification/attenuation of the input value. 

However we are in the context of a modular synth so attenuation/amplification is expected to be dealt with by the user with other modules.
My suggestion would be to just assign the CV a destination without offering any other option. Make it so that 0V does not affect the current values as it would work in any other analogue modules.
I would calibrate the inputs so we have the following behaviour :
When the length is set at minimum when the user send 5V the value goes to the max and If the rhythm is set to the maximum and the user sends -5V the value reaches the minimum.

**Comment by ArthurGibert** [comment]
Just as a little detail but I'm sure that you took this in account already but the module need to be connected to a Eurorack PSU to do any CV calibration. It relies on tl074 and a -10V ref which need the -12 to work properly.

**Comment by lucblender** [comment]
Note: this mean also removing cv scaling. Will only work on -5V 5V

**Comment by lucblender** [comment]
Note: we will need to clear the offset when changing cv a bit like the fix of #13 will be

**Comment by lucblender** [comment]
Fixed in 5ae6ee9 , can be tested in pre-release [v1.2.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.2.0_pre)
