### ISSUE TITLE
UI - Renaming

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#15]
v1.0.0

Renumber the Channels numbers to 1->4 (0->3 makes sense to the programmers but not to normal people, especially now that the CV are going from 1 to 4 and in the Outputs menu they are named Out1, 2 ,3, 4) 

In Config rename Pads -> Macro (or something else, Pads, looks like it would be setting parameters of the pads, like sensitivity for example)

In Config rename Other -> More

In the CV / Pad menu, rename Beat -> Length

In Other rename Outputs to Channels (then Ch1, Ch2... etc)

In Outputs menu rename prescaler -> clock division

**Comment by ArthurGibert** [comment]
rename the clock sources to internal/external

**Comment by lucblender** [comment]
Fixed in https://github.com/lucblender/lx-euclid-001/commit/555f301f992944902990a6a5eea2ed7032a44cdd, can be tested in pre-release [v1.1.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.1.0_pre)
