### ISSUE TITLE
UI - Move CV menu to channel Settings

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#16]
v1.0.0

I would move the CV assignment menu to the channel settings

Currently a few reasons come to mind

1 - This would remove the channel selection step of the CV assignment and streamline the process.

2 - Currently one chooses the destination and then the channel. This feels the wrong way around as it closes the user into having one CV affect the same parameter on multiple channel which feel a little arbitrarily limiting. It would be great to be able to have one CV affect for example the Fill of one while muting the other channel. 

3 - This feels like a better location as the CV only affect the channels and not general settings

4 - This allows to remove one item from the config menu and if the channel setting selection is also moved as [suggested here](https://github.com/lucblender/lx-euclid-001/issues/11#issuecomment-2298750943). 
The other menu contains only 2 items that could be moved one level up to the main config page, where we'd have Presets, Pads, Clk settings, Pad sensitivity. This would reduce the depts of submenu which is always a plus in my book.

**Comment by ArthurGibert** [comment]
I think it is important that one can affect multiple parameters of the same rhythm but also have the same CV affect multiple parameters.

Another point is that I think it  would be great to have a way to clear all CV assignments.

**Comment by lucblender** [comment]
Fixed in 639e41e, can be tested in pre-release [v1.4.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.4.0_pre)
