### ISSUE TITLE
Change color of Channel 2 to red

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#17]
v1.0.0

Purple/pink LEDs are very difficult to source.

**Comment by lucblender** [comment]
Fixed in https://github.com/lucblender/lx-euclid-001/commit/555f301f992944902990a6a5eea2ed7032a44cdd, can be tested in pre-release [v1.1.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.1.0_pre)
