### ISSUE TITLE
Raise default tempo to 120bpm

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#19]
v1.0.0

tempo is too slow by default raise tempo to the default 120bpm. 
That is a period of 125ms for 16th notes

**Comment by lucblender** [comment]
Fixed in https://github.com/lucblender/lx-euclid-001/commit/555f301f992944902990a6a5eea2ed7032a44cdd, can be tested in pre-release [v1.1.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.1.0_pre)
