### ISSUE TITLE
Enhancement - Mute and Fill

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#20]
v1.0.0

The way the Mute and Fill macro works currently doesn't really quite work with a live situation work flow. 

In a live context one would like to be able to mute and trigger fills on the channel of choice.

My idea would be that if one set Mute/Fill to a ring. One can then tap the up/right/down/left side of the ring to mute/fill channel 1, 2, 3, 4 respectively.

This would massively increase the useability of function.

Regarding visual feedback. When muting a channel, I would change the colour of this rhythm to grey. This caused confusion for me when I first used the function thinking that the fill was set to 0.

**Comment by lucblender** [comment]
Same should apply for reset so we only have one way to interact with macro that use "tap" action on circles

**Comment by lucblender** [comment]
Fixed in 639e41e, can be tested in pre-release [v1.4.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.4.0_pre)
