### ISSUE TITLE
Bug - Channels stopping when setting clock divide back to 1

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#24]
V1.1.0_dev

Channels stops when going back to clock divide by 1.

Steps to reproduce the behaviour:
Set to internal clock.

1 - Set clock divider (any number)  on CH1
2 - return to main page
3 - Set clock divider to 1 on CH1 - CH1 stops

This was also present on the other channels. Restarting the unit not always fixed the issue.

**Comment by ArthurGibert** [comment]
This seems to only be happening with the internal clock

**Comment by lucblender** [comment]
Fixed in 5ae6ee9 , can be tested in pre-release [v1.2.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.2.0_pre)
