### ISSUE TITLE
Fine tune the response of the lgth CV

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#34]
V1.5.0 pre

The CV response is linear leading to the CV pushing the lenght of the rhythm to the higher values

**Expected behavior**
As a the smaller length values are usually more usefull in Euclidian sequencers an exponetial response of this particular CV should make it more natural to use

**Comment by lucblender** [comment]
Test fix in https://github.com/lucblender/lx-euclid-001/commit/d292a690c41ec110e2e0aa38cb457aec4fcda45e , can be tested in pre-release [v1.6.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.6.0_pre)

**Comment by ArthurGibert** [comment]
I would make it even more exponential.
