### ISSUE TITLE
Preset recall modes

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#48]
V1.10.0

Would be great to be able to have the preset recall quantized to the reset triggers and also not have the preset reseted on recall (like previously)
Currently the reset recall is a bit twitchy as one need to precisely recall the new preset in between the last and first step to stay on time.

**If it's a feature enhancement**
This would be setting to add when in the preset page. 
When in the preset loading page - press config
Here are two item selection to select with the rings - Save and Mode
Mode allow to select between :
- direct w/ reset 
- direct wo/ reset
- on reset internal
- on reset external

**Comment by lucblender** [comment]
Can be tested in [v1.13.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.13.0_pre)

**Comment by lucblender** [comment]
Open to any nomenclature change. But will keep the two central circles :

> Maybe we can remove one of the central circle in the graphics to free up some space.

The circles have a meaning, in the whole UI you always see the two circles that correspond to the circular touchpads. If a circle is bright, it means that you can use it to interact with the UI.

**Comment by ArthurGibert** [comment]
Very happy with the different modes. They work well and are fun to use. They all have different pros and cons which is nice for experimenting.
