### ISSUE TITLE
Separate issue template between bug report and feature improvement 

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#49]
**Start with version of the firmware** - not applicable
 
Create a template to be able to make a feature suggestion/improvement 

Having to go though the bug report is not super intuitive.

**Comment by lucblender** [comment]
I added one a template by f0569594802f174fb289ece5f1b28ac6041b8a89. @ArthurGibert  can you test if it appears to you to and close the issue if it works?
