### ISSUE TITLE
Return to channel edit from the channel edit page

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#50]
V1.10.0

It is currently not possible to go back the the channel edit from channel edit page.

**Expected behavior**
When in the channel config page (and submenu) - One is currently able to change channel by pressing another channel button but it would be expected to be able to press the current channel button to be able to reach back the channel rhythm edit page. 

Currently one needs to first press the tap button and then the channel button once more to be able to edit a rhythm.

**Comment by lucblender** [comment]
The expected behavior has been made the following according to general UI navigation:
When in the channel config page (and submenu), pressing the config button return to back the channel rhythm edit page.

**Comment by lucblender** [comment]
Fixed in https://github.com/lucblender/lx-euclid-001/commit/8b56dff16f6c8fbb3d9318d56500fff957e9ce0c , can be tested [v0.10.2_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v0.10.2_pre)

**Comment by lucblender** [comment]
Fixed properly in https://github.com/lucblender/lx-euclid-001/commit/6069fffb68891e2234c2879daa2af3e54640412f, can be tested [v1.10.2_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.10.3_pre)
