### ISSUE TITLE
button test in Debug mode

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#55]
Firmware version V1.10.3

**Is your feature request related to a problem? Please describe.**
There is currently no way to check if the buttons work debug mode

**Describe the solution you'd like**
Have the button light up when pressed

**Comment by lucblender** [comment]
This feature is already included. In debug mode, the button light **turns off** when pressing it's pressed.

**Comment by ArthurGibert** [comment]
never mind then! I somehow didn't notice it when making the first batch... My bad
