### ISSUE TITLE
Feature request - Upside down mode

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#56]
Have the option of running the UI upside down

**Describe the solution you'd like**
Be able to have the display and the touchpad detection turned by 180 degrees.
This is by far the n1 feature requested in the comments.

**Comment by lucblender** [comment]
Can be tested in [v1.10.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.11.0_pre)

**Comment by ArthurGibert** [comment]
Works well and I haven't found any issues

**Comment by lucblender** [comment]
Now in release [v.14.1](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.14.1).
