### ISSUE TITLE
Feature request - Be able to set tempo in BPM

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#57]
**Is your feature request related to a problem? Please describe.**
Cinematic Laboratory & Marius have suggested that it would be nice to be able to set the internal speed of the sequencer in BPM 

**Describe the solution you'd like**
Go into clock source and have a BPM option. Set the outer ring for steps of 1 and the inner ring for steps of 10.
We could also event think of having this as a macro control

**Additional context**
This can be achieved with external clocking but it would be nice to be able to set it internally as the interface can handle it easy.

**Comment by lucblender** [comment]
idea - inner circle fine, outer circle coarse

**Comment by lucblender** [comment]
Can be tested in [v1.13.0_pre](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.13.0_pre)

**Comment by ArthurGibert** [comment]
BPM value should be divided by 4 to have values that make more sense to the user.

**Comment by lucblender** [comment]
> BPM value should be divided by 4 to have values that make more sense to the user.

That make sense, will do

**Comment by ArthurGibert** [comment]
This works well. No problem to report

**Comment by lucblender** [comment]
Now in release [v.14.1](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.14.1).
