### ISSUE TITLE
Offset ring

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#6]
in the latest release 0b3abb8 

Setting the offset is does not work the same way as the other setting. It uses the absolute position of the finger on the ring instead of working like an encoder like the other setting.

https://github.com/user-attachments/assets/7698b8df-6d02-42a2-a490-bb02731db4e9

**Comment by lucblender** [comment]
@ArthurGibert that is coded like that as a feature. Do you think it's better to have it like an encoder?

**Comment by ArthurGibert** [comment]
I don't dislike it but it's inconsistent and unexpected compared to the rest. 
Maybe it's a behavior we can change in the option menu?

**Comment by lucblender** [comment]
Fixed in v1.0.0 https://github.com/lucblender/lx-euclid-001/commit/00f5c699a63f208a8f88f8177a3688a401a87551
