### ISSUE TITLE
Faster access to "load preset" menu

### ISSUE THREAD

**Issue by lucblender** [lucblender/lx-euclid-001#62]
**Is your feature request related to a problem? Please describe.**
When doing live sessions, loading presets is important and I think it's too many clic/touch to load one. (Config->preset->preset number) 

I think the load preset menu should also be accessible in one easy action to not have to go menu diving during live sessions.

**Describe the solution you'd like**
Open load preset page on "long press" on config button.

**Describe alternatives you've considered**
Any other "one interaction" action to open that menu would be good.

**Comment by ArthurGibert** [comment]
That's a pretty good idea. 

Generally I'm not a big fan of the short press, long press sort of interaction but I think this could actually work nicelly

**Comment by ArthurGibert** [comment]
Works great! Speeds up the interraction a lot!
I would close the issue!

**Comment by lucblender** [comment]
Now in release [v.14.1](https://github.com/lucblender/lx-euclid-001/releases/tag/v1.14.1).
