### ISSUE TITLE
High priority - Inconsistent timing

### ISSUE THREAD

**Issue by ArthurGibert** [lucblender/lx-euclid-001#7]
See example. I first measure the latency while in the screen saver and it is consistent around 3ms which is not great but fine enough. Then when entering the menu the latency start jumping around going from around 3ms up 17ms.

This is of the highest priority. Latency should be at a minimum and the timing should be consistent. Timing should take priority over anything else and nothing should ever be allowed to affect it.

https://github.com/user-attachments/assets/af83851d-1bb7-40e3-af9b-ed5e4a878d9d

**Comment by lucblender** [comment]
@ArthurGibert Can you also test in
- rhythm edition menu
- properties menu

**Comment by ArthurGibert** [comment]
In rhythm edition menu  - the latency is only marginaly affected, being around 3.2ms

In property the menu - the max latency measured was 5.48ms

**Comment by ArthurGibert** [comment]
While in rhythm editing menu - sometime while touching the plate and changing the rhythm there are occasionally pulses that are being delayed to up to 25ms.
This was measure when editing Rhythm 0 and measured on rhythm 2 (sending triggers on every ticks) 

The module is clocked externally.

**Comment by lucblender** [comment]
Fixed in v1.0.0 https://github.com/lucblender/lx-euclid-001/commit/00f5c699a63f208a8f88f8177a3688a401a87551
